### ISSUE TITLE
More Mutators?

### ISSUE THREAD

**Issue by JimLynchCodes** [sourcefrog/cargo-mutants#113] opened 2023-04-20 03:44 UTC
Hi!

Thanks for making this is an awesome project!

I am just wondering though why "replacing function" is the only mutator available. 

Is it specifically the only mutator by design or is this still like an in-progress and not fully finished project?

This nice mutation testing tool for js, .net, and scala can go in and mutate individual lines, and in 30+ different ways! 🤓
https://stryker-mutator.io/docs/mutation-testing-elements/supported-mutators/

Any plans for adding these kinds of mutators to this project?

**Comment by sourcefrog** [comment] 2023-04-24 23:23
Yes, it's possible and I'm planning to add more, probably starting by
returning errors from functions that return a Result.

Did you try it with the current mutations on your projects? How did it go?

Martin

**Comment by sourcefrog** [comment] 2023-04-26 14:45
This is more or less a dupe of #73. The list of Stryker mutations is nice.

Adding more mutations is an obvious next step, but also, I think many packages have significant work to do to be fully tested just at the function level.

**Comment by sourcefrog** [comment] 2023-05-13 03:08
Closing as a dupe; please join in on #73 if you have more thoughts

**Closed by sourcefrog** 2023-05-13 03:08 UTC
