### ISSUE TITLE
Functions in Packages with custom `lib` names Undetected by Mutants

### ISSUE THREAD

**Issue by ASuciuX** [sourcefrog/cargo-mutants#185] opened 2023-12-14 23:43 UTC
[In this repository](https://github.com/stacks-network/stacks-core/tree/develop), I've been utilizing cargo mutants for testing. I noticed an issue where certain packages' functions weren't being detected. Specifically, this occurred in packages with custom-named lib files, like `libsigner` or `libclarity`, even though they were correctly listed in the Cargo.toml path. Interestingly, once these files were renamed to `lib`, they started working properly.

Is there a possibility to enhance implementation so that custom-named lib files are also recognized effectively?

Ref link: https://github.com/stacks-network/stacks-core/pull/4089#discussion_r1422394020 and [files renamed](https://github.com/stacks-network/stacks-core/pull/4089/files).

**Comment by sourcefrog** [comment] 2023-12-15 09:55
I actually recently fixed what I think is the same bug, in https://github.com/sourcefrog/cargo-mutants/pull/183. It just needs some test. Please try out that branch and let me know?

**Comment by sourcefrog** [comment] 2023-12-15 10:57
Probably a dupe of #115

**Comment by sourcefrog** [comment] 2023-12-15 20:34
Dupe of #115, fixed in #183, will be in a near future release

**Closed by sourcefrog** 2023-12-15 20:34 UTC
